### ISSUE TITLE
fmcalc max deductible not being applied for certain samples

### ISSUE THREAD

**Issue by benhayes21** [OasisLMF/ktools#55] opened 2019-07-16 16:04 UTC
Example provided to @johcarter where two locations with location deductibles of $1m each feed into a policy level max deductible of $1.5m, but the gross losses by location are GUL - $1m in each case.

Only applicable for certain sample simulations and not reproducible when the locations are run alone (i.e. outside of the full portfolio to which they belong)

**Comment by johcarter** [comment] 2019-07-17 15:45
Need to add test case

**Comment by johcarter** [comment] 2019-08-06 13:45
This is caused by a rounding error which invokes a new bit of fm code to handle over-limit/under-limit scenarios.
Where you have both wind and storm surge loss, the sum is reaching the coverage limit for certain samples.  Because of single precision rounding, it sometimes rounds it to just above the limit.
There is a new bit of code that handles adjustments to effective limits that have been applied in previous levels. this is being invoked and the logic appears to be a bit faulty.

In order to work around this, remove the application of coverage limit in level 1, or set the limit to something bigger. This cap is not needed for ARA because they already cap and back-allocate losses in their gulcalc module.

fyi @benhayes21

**Comment by johcarter** [comment] 2019-08-06 13:54
I will fix the code and add a test case fm52 to test the fix

**Comment by johcarter** [comment] 2019-08-19 09:00
code does not account for scenarios where some risks are over-limit and some are under-limit. its accumulating the over-limit surplus, but not the under-limit surplus. changing code to properly net the limit surplus (or -ve excess ) over the sum of risks in the grouping at level of the min or max deductible.

**Comment by johcarter** [comment] 2019-10-15 11:36
fixed in fix/over-and-under-limit

**Closed** 2020-01-23 16:37 UTC
Labels: bug
